theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "cpu"
interval = 10

[[block]]
block = "load"
interval = 10
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "battery"
interval = 60

[[block]]
block = "time"
interval = 60
format = "%Y-%m-%d %H:%M"
